=== MikhailKitikov/ComputerScience/Java/Employees database/validateXML.dtd
<!ELEMENT employees (employee)*>

<!ELEMENT employee (surname, position, salary)>

<!ELEMENT surname (#PCDATA)>
<!ELEMENT position (#PCDATA)>
<!ELEMENT salary (#PCDATA)>

=== MikhailKitikov/ComputerScience/Java/Employees database/data.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE employees SYSTEM "validateXML.dtd">

<employees>

	<employee>
		<surname>Petrov</surname>
		<position>MANAGER</position>
		<salary>150</salary>
	</employee>

	<employee>
		<surname>Sidorov</surname>
		<position>FIRSTCATEGORY</position>
		<salary>30</salary>
	</employee>

	<employee>
		<surname>Ivanov</surname>
		<position>DIRECTOR</position>
		<salary>300</salary>
	</employee>

	<employee>
		<surname>Sidorov</surname>
		<position>SECONDCATEGORY</position>
		<salary>10</salary>
	</employee>

	<employee>
		<surname>Petrova</surname>
		<position>MANAGER</position>
		<salary>160</salary>
	</employee>

	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>
	<employee>
		<surname>Petrova</surname>
		<position>DIRECTOR</position>
		<salary>180</salary>
	</employee>

</employees>
